Allow setting porcupine as your default browser
micahflee/porcupine pull request #7
Opened 2018-04-07 00:24 UTC by micahflee

Resolves #3.

This PR includes:

- Remove references to Windows and Mac. For now, porcupine is a Linux-only app
- Improve python styles
- Allows you to quit from the command line with Ctrl-C
- Finally, allows you to set porcupine as your default web browser (in Linux, of course)

Here's what the settings look like if it's not your default browser:

![screenshot_2018-04-06_17-20-27](https://user-images.githubusercontent.com/156128/38449044-40046514-39bf-11e8-96e7-20f433a90dc6.png)

And here's the settings if it is your default browser:

![screenshot_2018-04-06_17-24-15](https://user-images.githubusercontent.com/156128/38449062-5b920f70-39bf-11e8-84ea-407b5df6f789.png)

2018-04-19 05:13 UTC, edenemmanuel commented
The GUI asking to set the default browser looks great! However, at least on Debian, `xdg-settings set default-browser` doesn't seem to stick.

This seems to be a known bug in Debian (see [#576829](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=576829) in the Debian bug tracker). Indeed, trying manually to change my default browser in this method doesn't seem to actually work.

I have yet to try this on a Fedora system. I'll try to play with it on the latest Fedora and see if I can duplicate this problem there.

2018-04-19 05:16 UTC, anxiousnix requested changes

2018-04-19 05:16 UTC, anxiousnix commented on porcupine
> +        default_browser = subprocess.check_output(['xdg-settings', 'get', 'default-web-browser']).strip()
This works pretty swell! Can confirm this.

2018-04-19 05:16 UTC, anxiousnix commented on porcupine
> +        subprocess.call(['xdg-settings', 'set', 'default-web-browser', 'porcupine.desktop'])
This is where it seems to fail. On a Debian system, this doesn't seem to set. We'll need to find a way to change the default browser on Debian. It's possible!

2018-04-19 05:16 UTC, anxiousnix commented on porcupine
> -    elif getattr(sys, 'frozen', False):
Excellent. This should definitely remove the maintenance burden on us. We can always work on adding cross-platform support in the future.

2018-04-19 20:56 UTC, micahflee commented
Hmm weird, I'm trying to reproduce this issue in a Debian stretch appVM, but it just works for me there.

```sh
user@dev-debian ~ $ xdg-settings get default-web-browser
firefox-esr.desktop
user@dev-debian ~ $ xdg-settings set default-web-browser porcupine.desktop
user@dev-debian ~ $ xdg-settings get default-web-browser
porcupine.desktop
user@dev-debian ~ $ xdg-settings set default-web-browser firefox-esr.desktop
user@dev-debian ~ $ xdg-settings get default-web-browser
firefox-esr.desktop
user@dev-debian ~ $ 
```

Which version of Debian are you using? Maybe I should try installing it from ISO instead of basing it off of my Qubes template.

2018-05-01 18:44 UTC, micahflee commented
Here is the page of the chromium source code where it sets the default browser: https://github.com/chromium/chromium/blob/f18e79d901f56154f80eea1e2218544285e62623/chrome/browser/shell_integration.cc

2018-05-02 17:53 UTC, micahflee commented
I just tested this myself in a freshly installed Debian 9 with GNOME, and it seems to work! After you corroborate @edenemmanuel feel free to merge into develop

2018-05-08 01:09 UTC, edenemmanuel commented
Thanks @micahflee. I've tested this on Fedora 28 with GNOME 3.28 and Debian 9 with GNOME 3.22. Looks great to me!

2018-05-08 01:09 UTC, anxiousnix approved these changes

2018-05-08 21:36 UTC, merged